const tintColor = '#2f95dc';

export const lightColor = {
  springgreen:"springgreen",
  aqua:"aqua",
  lightseagreen:"lightseagreen",
  seagreen:"seagreen",
  limegreen:"limegreen",
  turquoise:"turquoise",
  royalblue:"royalblue",
  steelblue:"steelblue",
  cadetblue:"cadetblue",
  cornflowerblue:"cornflowerblue",
  rebeccapurple:"rebeccapurple",
  slateblue:"slateblue",
  olivedrab:"olivedrab",
  lightslategrey:"lightslategrey",
  aquamarine:"aquamarine",
  maroon:"maroon",
  gray:"gray",
  lightskyblue:"lightskyblue",
  blueviolet:"blueviolet",
  palegreen:"palegreen",
  yellowgreen:"yellowgreen",
  sienna:"sienna",
  lightblue:"lightblue",
  greenyellow:"greenyellow",
  paleturquoise:"paleturquoise",
  lightsteelblue:"lightsteelblue",
  powderblue:"powderblue",
  firebrick:"firebrick",
  rosybrown:"rosybrown",
  silver:"silver",
  peru:"peru",
  tan:"tan",
  lightgray:"lightgray",
  thistle:"thistle",
  orchid:"orchid",
  goldenrod:"goldenrod",
  palevioletred:"palevioletred",
  crimson:"crimson",
  gainsboro:"gainsboro",
  plum:"plum",
  burlywood:"burlywood",
  lightcyan:"lightcyan",
  lavender:"lavender",
  violet:"violet",
  lightcoral:"lightcoral",
  khaki:"khaki",
  honeydew:"honeydew",
  sandybrown:"sandybrown",
  wheat:"wheat",
  beige:"beige",
  fuchsia:"fuchsia",
  tomato:"tomato",
  hotpink:"hotpink",
  coral:"coral",
  lightsalmon:"lightsalmon",
  orange:"orange",
  lightpink:"lightpink",
  gold:"gold",
  blanchedalmond:"blanchedalmond",
  lavenderblush:"lavenderblush",
  lemonchiffon:"lemonchiffon",
  floralwhite:"floralwhite",
  yellow:"yellow",
};

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
};